//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ship.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.50;1239.30;1209.10;4.393;4.471;77.807;254.17;163.97
        ///0.51;1267.90;1237.00;4.394;4.470;76.454;254.87;163.99
        ///0.52;1296.50;1264.90;4.396;4.467;75.155;255.56;164.01
        ///0.53;1325.20;1292.90;4.397;4.464;73.906;256.21;164.02
        ///0.54;1353.90;1320.90;4.398;4.461;72.708;256.86;164.04
        ///0.55;1382.70;1348.90;4.399;4.459;71.552;257.50;164.06
        ///0.56;1411.50;1377.10;4.400;4.457;70.438;258.12;164.07
        ///0.57;1440.40;1405.20;4.401;4.455;69.192;258.67;164.09
        ///0.58;1469.30;1433.40;4.402;4.454;67.994;259.22;164.11
        ///0.59;1498.20;1461.70;4.403 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DraughtTable {
            get {
                return ResourceManager.GetString("DraughtTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.16;89.7
        ///5.4;89
        ///6.85;83.1
        ///10.37;71.7
        ///10.57;71
        ///10.97;69.8
        ///11.17;69
        ///12;66.23.
        /// </summary>
        internal static string FloodingAngleTable {
            get {
                return ResourceManager.GetString("FloodingAngleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.5;1.0
        ///3.0;1.08
        ///3.5;1.11
        ///4.0;1.11
        ///4;5;1.2
        ///5.0;1.3
        ///5.5;1.45
        ///6.0;1.56
        ///6.5;1.61.
        /// </summary>
        internal static string K0FactorTable {
            get {
                return ResourceManager.GetString("K0FactorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5;0.1
        ///6;0.1
        ///7;0.098
        ///8;0.093
        ///10;0.079
        ///12;0.065
        ///14;0.053
        ///16;0.044
        ///18;0.038
        ///20;0.035.
        /// </summary>
        internal static string SFactorTable {
            get {
                return ResourceManager.GetString("SFactorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.0;[0,0.707,1.413,2.107,2.781,3.422,3.992,4.465,4.866,5.217,5.52,5.788,6.029,6.245,6.441,6.619,6.781,6.93,7.066,7.191,7.304,7.408,7.5,7.585,7.661,7.73,7.793,7.849,7.899,7.944,7.983,8.017,8.047,8.072,8.093,8.11,8.124,8.133,8.139,8.141,8.14,8.136,8.13,8.12,8.107,8.092,8.074,8.054,8.032,8.007,7.98,7.952,7.922,7.891,7.858,7.824,7.789,7.753,7.717,7.68,7.643,7.606,7.57,7.534,7.499,7.465,7.434,7.405,7.379,7.358,7.341,7.329,7.325,7.328,7.342,7.367,7.405,7.46,7.518,7.574,7.628,7.683,7.741,7.801,7.857,7.914,7.969,8. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string StabilityCurveTable {
            get {
                return ResourceManager.GetString("StabilityCurveTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2;3102.6;11.115
        ///2.5;3019.5;11.136
        ///3;2936.2;11.160
        ///3.5;2852.3;11.187
        ///4;2768.4;11.215
        ///4.5;2685.2;11.243
        ///5;2602.3;11.271
        ///5.5;2519.6;11.301
        ///6;2437.1;11.332
        ///6.5;2354.8;11.364
        ///7;2272.5;11.399
        ///7.5;2190.3;11.436
        ///8;2107.5;11.478
        ///8.5;2024.0;11.527
        ///9;1939.6;11.582
        ///9.5;1854.3;11.646
        ///10;1768.8;11.718
        ///10.5;1683.1;11.797
        ///11;1597.2;11.886
        ///11.5;1511.3;11.984
        ///12;1425.3;12.096.
        /// </summary>
        internal static string WindageAreaTable {
            get {
                return ResourceManager.GetString("WindageAreaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.4;1.0
        ///2.6;0.96
        ///2.8;0.93
        ///3.0;0.9
        ///3.2;0.86
        ///3.4;0.82
        ///3.5;0.8.
        /// </summary>
        internal static string X1FactorTable {
            get {
                return ResourceManager.GetString("X1FactorTable", resourceCulture);
            }
        }
    }
}
